name: Cron

on:
  workflow_dispatch:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: cron
    steps:
      - name: Initialize
        env:
          SRR_CDN_URL: ${{ vars.SRR_CDN_URL }}
        run: |
          set -x
          wget -qP packs "$SRR_CDN_URL/db.json"
          LATEST=$( jq .latest packs/db.json )
          wget -qP packs "$SRR_CDN_URL/$LATEST.gz" || :

          BIN=$( curl -s "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases/latest" | jq -r '.assets[].browser_download_url' )
          wget -qO srr "$BIN"
          chmod +x srr
      - name: Fetch
        run: ./srr fetch
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
          AWS_DEFAULT_REGION: weur
        run: |
          cd packs
          aws s3 cp --recursive . s3://srr
