name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - run: CGO_ENABLED=0 go build -ldflags "-s -w" -o srr .
    - uses: softprops/action-gh-release@v2
      with:
        files: srr